source 'https://rubygems.org'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'

# Component requirements
gem 'slim'
# gem 'pg', :group => 'production'
# gem 'dm-postgres-adapter', :group => 'production'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-constraints'
gem 'dm-aggregates'
gem 'dm-types'
gem 'dm-core'
gem 'tilt','1.3.4'

group :test do
  gem 'dm-sqlite-adapter'
  gem 'rspec'
  gem 'cucumber'
  gem 'capybara'
  gem 'rack-test', :require => 'rack/test', :group => 'test'
end
# Test requirements

# Padrino Stable Gem
gem 'padrino', '0.11.1'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.11.1'
# end
