source 'http://rubygems.org'
gem 'sinatra'
gem "unicorn"
gem "rack"
gem "rake"
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'json'
gem 'omniauth'
gem 'omniauth-twitter'

group :test do
  gem 'sqlite3'
  gem "rspec_junit_formatter"
  gem 'simplecov'
  gem 'cucumber-sinatra'
  gem 'cucumber', '1.1.9'
  gem 'capybara'
  gem 'rspec'
  gem 'therubyracer'
  gem "jshintrb"
end
